# Generated by Django 3.0.8 on 2022-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deltaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('meting_id', models.CharField(max_length=20)),
                ('WP_IN', models.FloatField()),
                ('WP_UIT', models.FloatField()),
                ('delta_WP', models.FloatField()),
                ('BC_ww_IN', models.FloatField()),
                ('BC_ww_UIT', models.FloatField()),
                ('delta_BC', models.FloatField()),
                ('VloerVerw_IN', models.FloatField()),
                ('VloerVerw_UIT', models.FloatField()),
                ('delta_VloerVerw', models.FloatField()),
                ('flow_WP', models.FloatField()),
                ('flow_WW_BC', models.FloatField()),
                ('flow_VloerVerw', models.FloatField()),
                ('H2_massa_flow', models.FloatField()),
                ('Temperatuur_hal', models.FloatField()),
                ('Temperatuur_BC_uitlaat', models.FloatField()),
                ('driewegklep_BC', models.FloatField()),
                ('BC_intern_T1', models.FloatField()),
                ('driewegklep_WP', models.FloatField()),
                ('geleverd_vermogen_therm', models.FloatField()),
                ('opgenmoen_vermogen_el', models.FloatField()),
                ('Accu_spanning', models.FloatField()),
                ('Accu_stroom', models.FloatField()),
                ('Accu_SOC', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Metingen',
            },
        ),
    ]
