# Generated by Django 3.2.7 on 2021-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210920_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltastatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
