# Generated by Django 3.2.7 on 2021-09-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_deltastatus_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deltastatus',
            options={'verbose_name_plural': 'Metingen'},
        ),
    ]
