# Generated by Django 3.1.7 on 2021-10-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_deltastatus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltastatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
