# Generated by Django 3.1.7 on 2021-09-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_id'),
        ('user_profile', '0003_alter_profile_id'),
    ]

    operations = [
    ]
